### ISSUE TITLE
Incremental models cannot full_refresh

### ISSUE THREAD

**Issue by DezeriusCsanadLevay** [microsoft/dbt-fabric#179]
When I run an incremental model with --full-refresh it throws and error that table already exist.
It doesn't matter which on_schema_change route I choose. I always have to manually drop the table to do a full refresh.
![image](https://github.com/microsoft/dbt-fabric/assets/166915684/58581773-7914-457b-ab54-9ff74ed3a63f)

Am I missing something or is this a bug?

**Comment by prdpsvs** [comment]
@DezeriusCsanadLevay , Could you please share a repro please? I will repro at my end and will fix this issue.

**Comment by M4Al** [comment]
I observe the same bug here :(

**Comment by DezeriusCsanadLevay** [comment]
> @DezeriusCsanadLevay , Could you please share a repro please? I will repro at my end and will fix this issue.

I cannot share the exact repo (because it's private), but I recreated the issue with jaffleshop:
![image](https://github.com/microsoft/dbt-fabric/assets/166915684/0911caa0-43aa-4399-b3bb-5833a8555120)

Here's the repo:
https://github.com/DezeriusCsanadLevay/jaffle-shop-classic.git

**Comment by byrontuckett** [comment]
@prdpsvs Heads up that this issue is affecting dbt-synapse 1.8.1.

dbt-synapse 1.8.1  is requiring `dbt-fabric==1.8.6`. While the fixes are in dbt-fabric 1.8.7, which have [been committed to the main branch](https://github.com/microsoft/dbt-synapse/commit/8867f8351cd8100777366fb5e76b8d9f86f64e47), a release has not been cut yet to effect this change.  

Would you kindly create a patch release so this fixes can be included for dnbt-synapse.  Currently dbt--synapse users are unable to use `--full-refresh` with incremental models.
