### ISSUE TITLE
adding dbt sources from lakehouse

### ISSUE THREAD

**Issue by wisemuffin** [microsoft/dbt-fabric#70]
# Overview

I am looking to setup an architecture in fabric that has a warehouse that sits ontop of a lakehouse. As described in [Lakehouse vs Warehouse](https://publicstoragejs.blob.core.windows.net/presentations/Microsoft%20Fabric%20-%20Lakehouse%20vs%20Warehouse%20-%20James%20Serra.pdf)

I am looking to land raw data into the lakehouse and do some staging with pyspark in the lakehouse. But i want to do all my business logic and semantic modeling in the warehouse with DBT,

To enable this i am looking at setting up [dbt sources.yml](https://docs.getdbt.com/docs/build/sources) that points to a lakehouse (in the same fabric workspace). 

## Request

In a Fabric warehouse we can have queries that reference the warehouse e.g.

```sql
create view <warehouse_db>.<warehouse_schema>.<warehouse_view> as (
select * from <lakehouse_name>.<lakehouse_table>
)
```

I would like to add the lakehouse objects to [dbt sources.yml](https://docs.getdbt.com/docs/build/sources) so that my DBT models in the warhouse can use `ref(<source_lakehouse_table_name>)` function

**Comment by thebroberts** [comment]
Hello - since the Lakehouse and Warehouse are in the same workspace, this can be done using the `database` property in `source.yml`:

`lh_source.yml`
```
version: 2

sources:
  - name:  my_lakehouse
    database: FabricLakehouseName
    schema:  dbo
    tables:
      - name:  my_lakehouse_table
        columns:

          - name: id
         (etc...)
```

In your model, use a `source()` instead of `ref()`:

`lh_model.sql`
```
select * from {{source("my_lakehouse", "my_lakehouse_table")}}
```

The model compiles to:
```
create view "my_schema"."lh_model" as select * from "FabricLakehouseName"."dbo"."my_lakehouse_table"
```
This model ran successfully and I was able to see and query the new view in the Warehouse.

This works because each workspace has only one SQL endpoint, and the various Lakehouses / Warehouses in that workspace are presented in the same way as multiple databases behind a single SQL Server. Connect to the Workspace endpoint with SSMS and you'll see exactly what I mean.

Hope that helps!

**Comment by wisemuffin** [comment]
thank you @thebroberts this makes a lot of sense now.

**Comment by prdpsvs** [comment]
@wisemuffin , I am closing this issue as your question is addressed by @thebroberts .
Thank you @thebroberts .
